# Generated by Django 4.2.13 on 2024-06-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_order_date_delivery_order_is_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproduct',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='imageproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
