# Generated by Django 4.2.13 on 2024-06-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0003_rename_image_id_imageproduct_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
