# Generated by Django 4.2.13 on 2024-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0004_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='appsite.OrderProduct', to='appsite.product'),
        ),
    ]
